### ISSUE TITLE
license of your todo project (fork of MIT licensed toukan)?

### ISSUE THREAD

**Issue by LifeCANvs** [cklukas/C--#1]
Hi. I am interested in the TUI kanban project that you have forked and continued to work on... it does not however include a license anywhere on the repo info, readme or in the source files. Sorry for opening an issue about it in another one of your projects, however the todo repo does not have "issues" enabled.

**Comment by cklukas** [comment]
I added the license file and will check why the issues are not available in the other project. Thanks for your message and interest :-)

**Comment by LifeCANvs** [comment]
Thank you so much.
